In [13]:
import numpy as np

# creating 1D, 2D, 3D and nD array

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr1.ndim

1

In [14]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 3)

In [17]:
arr2.size

6

In [6]:
arr2 = np.array([[1,2,3],[4,5]])
arr2

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [7]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
arr3.ndim

3

In [9]:
arr6 = np.array([1,2,3], ndmin=6)
arr6

array([[[[[[1, 2, 3]]]]]])

In [10]:
arr6.ndim

6

# zeros

In [11]:
arr_zeros = np.zeros(4)
arr_zeros

array([0., 0., 0., 0.])

In [12]:
arr_zeros = np.zeros((2,3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

# ones

In [3]:
arr_ones = np.ones(4)
arr_ones

array([1., 1., 1., 1.])

In [4]:
arr_ones = np.ones((2,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

# empty

In [5]:
arr_empty = np.empty(4) 
arr_empty # hold old value from memory

array([1., 1., 1., 1.])

In [6]:
arr_empty = np.empty((2,3)) 
arr_empty # hold old value from memory

array([[1., 1., 1.],
       [1., 1., 1.]])

# np.full()

The `np.full()` function in NumPy creates a new array of a specified shape and fills it with a specified value. It's particularly useful when you need an array initialized with a constant value for operations or as a placeholder.

In [18]:
arr = np.full((2, 3), 7)
arr

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
arr = np.full(5, 10)  # Shape is just an integer for 1D
arr

array([10, 10, 10, 10, 10])

# arange

In [7]:
arr_rng = np.arange(5)
arr_rng

array([0, 1, 2, 3, 4])

In [8]:
arr_rng = np.arange(5,10)
arr_rng

array([5, 6, 7, 8, 9])

In [9]:
arr_rng = np.arange(5,10,2)
arr_rng

array([5, 7, 9])

# diagonal

In [10]:
arr_diagonal = np.eye(3)
arr_diagonal

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr_diagonal = np.eye(3,5) # not tuple in this case
arr_diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

# linspace

`np.linspace()` is a NumPy function used to generate an array of evenly spaced numbers over a specified interval. It's especially useful when you need a specific number of evenly spaced points between two endpoints, which can be helpful in scenarios like plotting graphs or working with mathematical functions.

In [12]:
import numpy as np

arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
# Excluding the Endpoint

arr = np.linspace(0, 10, 5, endpoint=False)
arr

array([0., 2., 4., 6., 8.])

In [14]:
# Returning the Step Size

arr, step = np.linspace(0, 10, 5, retstep=True)
step # difference between each number

np.float64(2.5)

In [15]:
arr = np.linspace(0, 1, 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [16]:
arr = np.linspace(0, 10, 5, dtype=int)
arr

array([ 0,  2,  5,  7, 10])

# rand(), randn(), randf() and randint()

In NumPy, the functions rand(), randn(), random(), and randint() are used for generating random numbers, but they serve different purposes based on the types and distributions of the numbers they generate.

## rand() (Uniform Distribution)

The `np.random.rand()` function generates random numbers from a uniform distribution over the interval [0, 1). This means each number in the specified range has an equal probability of being selected.

In [20]:
import numpy as np

# Generate a single random number between 0 and 1
single_rand = np.random.rand()
print(single_rand)  

0.19545536587406032


In [21]:
# Generate a 2x3 array of random numbers between 0 and 1
rand_arr = np.random.rand(2, 3)
print(rand_arr)


[[0.20221977 0.94996418 0.07626957]
 [0.31528589 0.19384    0.68206279]]


## randn() (Standard Normal Distribution)

The `np.random.randn()` function generates random numbers from a standard normal distribution (Gaussian distribution) with a mean of 0 and a standard deviation of 1. This distribution is bell-shaped, where most numbers will be around 0, with fewer numbers further from 0.

In [22]:
# Generate a single random number from the standard normal distribution
single_randn = np.random.randn()
print(single_randn)

-0.8132152374784997


In [23]:
# Generate a 2x3 array of random numbers from the standard normal distribution
randn_arr = np.random.randn(2, 3)
print(randn_arr)

[[-0.39646538  0.23556612 -0.23416182]
 [-0.99343628 -1.18635164 -1.61023132]]


## random() (Alias for rand())

In NumPy, `np.random.random()` is simply an alias for `np.random.rand()` and works the same way.

In [24]:
# Generate a single random number between 0 and 1
single_random = np.random.random()
print(single_random)

0.09628997097620373


In [25]:
# Generate a 2x3 array of random numbers between 0 and 1
random_arr = np.random.random((2, 3))
print(random_arr)

[[0.99701768 0.03335512 0.42185423]
 [0.84246827 0.93079274 0.52880986]]


## randint() (Random Integers)

The `np.random.randint()` function generates random integers between a specified range (inclusive of the lower bound and exclusive of the upper bound).

In [ ]:
np.random.randint(low, high=None, size=None, dtype=int)

In [26]:
# Generate a single random integer between 1 (inclusive) and 10 (exclusive)
single_randint = np.random.randint(1, 10)
print(single_randint)  # Output: e.g., 7

6


In [27]:
# Generate a 2x3 array of random integers between 1 (inclusive) and 10 (exclusive)
randint_arr = np.random.randint(1, 10, size=(2, 3))
print(randint_arr)

[[3 7 7]
 [9 8 2]]


# datatype

In [28]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [29]:
arr = np.array([1,2,3,4], dtype='int8')
arr.dtype

dtype('int8')

In [30]:
arr = np.array([1,2,3,4], dtype=np.int8)
arr.dtype

dtype('int8')

In [31]:
arr = np.array([1,2,3,4], dtype=np.float64)
arr.dtype

dtype('float64')

In NumPy, data types (also known as dtypes) are crucial as they determine how the data is stored in memory, processed, and interpreted. NumPy provides a wide range of data types, making it efficient for numerical operations and array manipulations. Here’s an overview of data types in NumPy.

## Common NumPy Data Types (Dtypes)

- Integers: These are whole numbers.
    - int8: 8-bit integer (-128 to 127)
    - int16: 16-bit integer (-32,768 to 32,767)
    - int32: 32-bit integer (-2,147,483,648 to 2,147,483,647)
    - int64: 64-bit integer (very large range)

- Unsigned Integers: These are whole numbers, but only positive values.
    - uint8: 8-bit unsigned integer (0 to 255)
    - uint16: 16-bit unsigned integer (0 to 65,535)
    - uint32: 32-bit unsigned integer (0 to 4,294,967,295)
    - uint64: 64-bit unsigned integer (very large range)

- Floating Point Numbers: These represent real numbers with decimals.
    - float16: Half-precision floating point (smaller range and less precision)
    - float32 (or just float): Single-precision floating point
    - float64 (or just double): Double-precision floating point (default for real numbers in NumPy)

- Complex Numbers: These represent numbers with both real and imaginary parts.
    - complex64: Complex number, represented by two 32-bit floats (real and imaginary parts)
    - complex128: Complex number, represented by two 64-bit floats (real and imaginary parts)

- Boolean: Used to represent True or False values.
    - bool: Boolean type, stores True or False

- String: Used to represent text data.
    - str_: Fixed-length Unicode type (e.g., '<U10' means a Unicode string of maximum length 10)

- Object: Used for arbitrary Python objects.
    - object: A generic object type, can hold any Python object (less efficient than other types)

- Datetime and Timedelta: Used for handling date and time data.
    - datetime64: Represents dates and times with a fixed precision (e.g., np.datetime64('2023-09-24'))
    - timedelta64: Represents time differences (e.g., np.timedelta64(1, 'D'))

**`astype()` is used to change an array’s data type:**

In [ ]:
# change the data type of an existing array using the astype() function:

arr = np.array([1, 2, 3], dtype=np.int32)
print(arr)

# Convert to float
arr_float = arr.astype(np.float64)
print(arr_float)  # Output: [1. 2. 3.]
print(arr_float.dtype)  # Output: float64

**Example of Different Dtypes in NumPy Arrays:**

In [ ]:
# Integer array
int_arr = np.array([1, 2, 3], dtype=np.int8)
print(int_arr, int_arr.dtype)  # Output: [1 2 3] int8

# Float array
float_arr = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(float_arr, float_arr.dtype)  # Output: [1. 2. 3.] float32

# Boolean array
bool_arr = np.array([True, False, True], dtype=np.bool_)
print(bool_arr, bool_arr.dtype)  # Output: [ True False  True] bool

# Complex array
complex_arr = np.array([1+2j, 3+4j], dtype=np.complex128)
print(complex_arr, complex_arr.dtype)  # Output: [1.+2.j 3.+4.j] complex128

## Custom Data Types (Structured Arrays)

NumPy also supports creating custom or compound data types (structured arrays) by defining a structured dtype.

In [21]:
# Define a structured data type with fields: name (string), age (integer), and score (float)
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('score', 'f4')])

# Create an array with that data type
students = np.array([('Alice', 21, 85.5), ('Bob', 25, 90.0)], dtype=dt)
print(students)
# Output: [('Alice', 21, 85.5) ('Bob', 25, 90.)]

[('Alice', 21, 85.5) ('Bob', 25, 90. )]


# shape and reshape

In [22]:
arr_1d = np.array([1, 2, 3, 4])
arr_1d.shape

(4,)

In [23]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d.shape  

(2, 3)

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape((2, 3))
arr_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# 2D array
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape to a 3D array (2 layers of 1x3)
arr_reshaped_3d = arr_2d.reshape(2, 1, 3)
arr_reshaped_3d

array([[[1, 2, 3]],

       [[4, 5, 6]]])

You can use `-1` in one of the dimensions to have NumPy automatically calculate that dimension based on the size of the data and the other specified dimensions.

In [26]:
# Using -1 to Let NumPy Infer a Dimension

arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Let NumPy automatically calculate the number of rows
arr_reshaped = arr_1d.reshape(-1, 3)
arr_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

# arithmetic operation

In [35]:
arr = np.array([1, 2, 3, 4])

# Element-wise addition
arr_add = arr + 10
print(arr_add)  # Output: [11 12 13 14]

# Element-wise substraction
arr_sub = arr - 1
print(arr_sub)  # Output: [0 1 2 3]

# Element-wise multiplication
arr_mul = arr * 2
print(arr_mul)  # Output: [2 4 6 8]

# Element-wise division
arr_div = arr / 2
print(arr_div)  # Output: [0.5 1.  1.5 2. ]

# Element-wise square
arr_square = arr ** 2
print(arr_square)  # Output: [ 1  4  9 16]


[11 12 13 14]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [28]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
result = arr1 + arr2
print(result)  # Output: [5 7 9]

# Using np.add()
result = np.add(arr1, arr2)
print(result)  # Output: [5 7 9]

[5 7 9]
[5 7 9]


In [29]:
# Element-wise subtraction
result = arr2 - arr1
print(result)  # Output: [3 3 3]

# Using np.subtract()
result = np.subtract(arr2, arr1)
print(result)  # Output: [3 3 3]

[3 3 3]
[3 3 3]


In [30]:
# Element-wise multiplication
result = arr1 * arr2
print(result)  # Output: [4 10 18]

# Using np.multiply()
result = np.multiply(arr1, arr2)
print(result)  # Output: [4 10 18]

[ 4 10 18]
[ 4 10 18]


In [31]:
# Element-wise division
result = arr2 / arr1
print(result)  # Output: [4.  2.5 2. ]

# Using np.divide()
result = np.divide(arr2, arr1)
print(result)  # Output: [4.  2.5 2. ]

[4.  2.5 2. ]
[4.  2.5 2. ]


In [32]:
# Element-wise exponentiation
result = arr1 ** 2
print(result)  # Output: [1 4 9]

# Using np.power()
result = np.power(arr1, 2)
print(result)  # Output: [1 4 9]

[1 4 9]
[1 4 9]


In [33]:
# Element-wise modulus
result = arr2 % arr1
print(result)  # Output: [0 1 0]

# Using np.mod()
result = np.mod(arr2, arr1)
print(result)  # Output: [0 1 0]

[0 1 0]
[0 1 0]


In [34]:
# Element-wise floor division
result = arr2 // arr1
print(result)  # Output: [4 2 2]

# Using np.floor_divide()
result = np.floor_divide(arr2, arr1)
print(result)  # Output: [4 2 2]

[4 2 2]
[4 2 2]


# broadcasting

NumPy supports broadcasting, which allows operations on arrays of different shapes as long as certain compatibility rules are met. For example, you can add a scalar to a vector, or a smaller array to a larger array if their shapes are compatible.

In [62]:
arr1 = np.array([1, 2, 3])
scalar = 2

# Adding a scalar to an array
result = arr1 + scalar
print(result)  # Output: [3 4 5]

[3 4 5]


In [37]:
# Multiplying a 1D array with a 2D array
arr2d = np.array([[1, 2], [3, 4], [5, 6]])
result = arr1[:, np.newaxis] * arr2d
print(result)

[[ 1  2]
 [ 6  8]
 [15 18]]


In [38]:
arr1[:, np.newaxis]

# np.newaxis is used to add a new axis along the columns, transforming arr1 from a 1D array of shape (3,) to a 2D array of shape (3, 1).

array([[1],
       [2],
       [3]])

Without `np.newaxis`, the shapes of the arrays wouldn't align for broadcasting, and the operation would raise an error. Adding the new axis allows you to perform operations between arrays with different shapes in a straightforward and memory-efficient way.

### Broadcasting Rules

Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" them to be compatible. This is a powerful feature for handling operations efficiently without explicitly creating large arrays.

**Broadcasting Rules:**
                                                                                                                                               
1. Rule 1: Dimensions Must Match or Be 1

    - If two arrays have different shapes, compare their shapes element-wise from the rightmost dimension.
    - Two dimensions are compatible if:
        - They are equal.
        - One of them is 1.
                                                                                                                                               
2. Rule 2: Automatically Expand Dimensions with Size 1

    - If a dimension of size 1 exists, NumPy will broadcast (replicate) the data along that dimension.

3. Rule 3: If Shapes Are Incompatible, Broadcasting Fails

    - If neither dimension is 1, nor are they equal, broadcasting throws an error.


In [39]:
import numpy as np

arr1 = np.array([1, 2, 3])      # Shape: (3,)
arr2 = np.array([[10], [20]])   # Shape: (2, 1)

result = arr1 + arr2            # Broadcasting occurs
result

# Explanation:

# arr1 has shape (3,).
# arr2 has shape (2, 1).
# After broadcasting, arr2 becomes [[10, 10, 10], [20, 20, 20]].

array([[11, 12, 13],
       [21, 22, 23]])

# indexing

In [36]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print(arr[0])  # Output: 10 (first element)
print(arr[2])  # Output: 30 (third element)

# Negative indexing
print(arr[-1])  # Output: 50 (last element)
print(arr[-2])  # Output: 40 (second last element)

10
30
50
40


In [37]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access element in the first row, second column [row, column]
print(arr_2d[0, 1])  # Output: 2

# Access element in the last row, last column
print(arr_2d[-1, -1])  # Output: 9

2
9


# slicing

Slicing allows you to extract subarrays from an array. The syntax for slicing is similar to that in Python lists: `start:stop:step`.

Note that `stop` is not included in output

In [38]:
arr = np.array([10, 20, 30, 40, 50])

# Slicing elements from index 1 to 3 (excluding 4)
print(arr[1:4])  # Output: [20 30 40]

# Slicing with a step of 2
print(arr[0:5:2])  # Output: [10 30 50]

# Slicing from the beginning to the third element
print(arr[:3])  # Output: [10 20 30]

# Slicing from the third element to the end
print(arr[2:])  # Output: [30 40 50]

# Reverse slicing
print(arr[::-1])  # Output: [50 40 30 20 10]

[20 30 40]
[10 30 50]
[10 20 30]
[30 40 50]
[50 40 30 20 10]


In [39]:
# For 2D arrays, you can slice rows and columns using : for each axis.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice the first two rows and the first two columns
print(arr_2d[:2, :2])
# Output:
# [[1 2]
#  [4 5]]

# Slice all rows but only the second and third columns
print(arr_2d[:, 1:3])
# Output:
# [[2 3]
#  [5 6]
#  [8 9]]

# Slice the last two rows
print(arr_2d[1:, :])
# Output:
# [[4 5 6]
#  [7 8 9]]

[[1 2]
 [4 5]]
[[2 3]
 [5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]


In [40]:
# For 3D arrays, you slice along three axes (depth, rows, columns).

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Slice all depth layers, the first row, and the first column
print(arr_3d[:, 0, 0])
# Output: [1 5]

# Slice the first depth layer and all rows and columns
print(arr_3d[0, :, :])
# Output:
# [[1 2]
#  [3 4]]

[1 5]
[[1 2]
 [3 4]]


**You can modify parts of a NumPy array by using indexing and slicing:**

In [41]:
arr = np.array([10, 20, 30, 40, 50])

# Modify the first element
arr[0] = 100
print(arr)  # Output: [100  20  30  40  50]

# Modify a slice of the array
arr[1:4] = [200, 300, 400]
print(arr)  # Output: [100 200 300 400  50]

[100  20  30  40  50]
[100 200 300 400  50]


In [42]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Modify an element
arr_2d[1, 2] = 10
print(arr_2d)
# Output:
# [[ 1  2  3]
#  [ 4  5 10]
#  [ 7  8  9]]

# Modify a slice
arr_2d[0:2, 1:3] = [[20, 30], [50, 60]]
print(arr_2d)
# Output:
# [[ 1 20 30]
#  [ 4 50 60]
#  [ 7  8  9]]

[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]
[[ 1 20 30]
 [ 4 50 60]
 [ 7  8  9]]


## boolean indexing

You can use boolean conditions to extract elements from an array that satisfy certain conditions.

In [43]:
arr = np.array([10, 20, 30, 40, 50])

# Get elements greater than 30
result = arr[arr > 30]
print(result)  # Output: [40 50]

# Replace all elements greater than 30 with 100
arr[arr > 30] = 100
print(arr)  # Output: [ 10  20  30 100 100]

[40 50]
[ 10  20  30 100 100]


## Fancy Indexing

Fancy indexing allows you to access multiple elements at once using a list of indices.

In [44]:
arr = np.array([10, 20, 30, 40, 50])

# Access elements at index 0, 2, and 4
result = arr[[0, 2, 4]]
print(result)  # Output: [10 30 50]

# 2D array fancy indexing
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
result = arr_2d[[0, 1], [1, 0]]  # Access (0, 1) and (1, 0)
print(result)  # Output: [2 3]

[10 30 50]
[2 3]


# np.where

np.where is a versatile function in NumPy used for conditional indexing and element-wise selection based on a condition. It allows you to:

1. Find the indices of elements that satisfy a condition.
2. Conditionally select values from two arrays based on a boolean condition.

**Syntax:** np.where(condition, [x, y])

    - condition: A boolean array or an expression that evaluates to a boolean array.
    - x and y (optional): Values to select from when the condition is True or False

In [46]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30])
indices = np.where(arr > 20)
print(indices)

(array([3, 4]),)


If x and y are provided, np.where returns an array where:

    - Values from x are selected when the condition is True.
    - Values from y are selected when the condition is False.

In [47]:
arr = np.array([10, 15, 20, 25, 30])
result = np.where(arr > 20, arr, -1)
print(result)

[-1 -1 -1 25 30]


In [48]:
# Replace all even numbers in an array with 0

arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr % 2 == 0, 0, arr)
print(result)

[1 0 3 0 5]


In [49]:
# Replace numbers greater than 20 or divisible by 5 with -1

arr = np.array([10, 15, 20, 25, 30])
result = np.where((arr > 20) | (arr % 5 == 0), -1, arr)
print(result)

[-1 -1 -1 -1 -1]


# np.take

The np.take function selects elements from an array based on given indices. It is useful for advanced indexing and slicing.

**Syntax:** np.take(arr, indices, axis=None)

    - arr: Input array.
    - indices: List or array of indices to extract.
    - axis: The axis along which to extract elements. If None, the array is flattened first.

In [50]:
arr = np.array([10, 20, 30, 40])
result = np.take(arr, [0, 2])
print(result)

[10 30]


In [65]:
arr = np.array([[10, 20], [30, 40]])
result = np.take(arr, [0, 1], axis=0)
print(result)

[[10 20]
 [30 40]]


In [66]:
arr = np.array([[10, 20], [30, 40]])
result = np.take(arr, [0, 1], axis=1)
print(result)

[[10 20]
 [30 40]]


**Benefits of `np.take`:**
- Handles multi-dimensional arrays cleanly.
- Can extract elements along any axis.

# np.put

The np.put function modifies specific elements of an array in-place by providing indices and values.

**Syntax:** np.put(arr, indices, values, mode='raise')

- arr: Target array.
- indices: List of flat indices where values should be placed.
- values: Values to insert at specified indices.
- mode: Behavior when indices are out of bounds:
    - 'raise': Throws an error (default).
    - 'wrap': Wraps indices.
    - 'clip': Clips indices to the valid range.


In [53]:
arr = np.array([10, 20, 30, 40])
np.put(arr, [0, 3], [100, 400])
print(arr)

[100  20  30 400]


In [54]:
arr = np.array([10, 20, 30, 40])
np.put(arr, [4, 5], [100, 200], mode='wrap')
print(arr)


[100 200  30  40]


In [55]:
# Replace elements greater than 20 with 0 using np.put

arr = np.array([10, 25, 30, 15])
indices = np.where(arr > 20)
np.put(arr, indices, 0)
print(arr)

[10  0  0 15]


# Aggregation Functions

In [40]:
arr = np.array([[1, 2], [3, 4]])

print(np.sum(arr))       # Total sum

print(np.sum(arr, axis=0))  # Sum along columns
print(np.sum(arr, axis=1))  # Sum along rows

10
[4 6]
[3 7]


In [41]:
arr = np.array([1, 2, 3, 4])

print(np.mean(arr))

2.5


In [42]:
arr = np.array([10, 20, 30, 40])

print(np.median(arr))

25.0


In [43]:
arr = np.array([1, 2, 3, 4])

print(np.std(arr))  # Standard deviation
print(np.var(arr))  # Variance

1.118033988749895
1.25


In [ ]:
arr = np.array([[1, 2], [3, 4]])

print(np.min(arr))        # Minimum value
print(np.max(arr))        # Maximum value

print(np.min(arr, axis=0))  # Minimum along columns
print(np.max(arr, axis=1))  # Maximum along rows

### Axis-Based Operations

In NumPy, the axis parameter defines the direction of computation:

- axis=0: Operation is applied column-wise (vertically).
- axis=1: Operation is applied row-wise (horizontally).

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum along columns
print(np.sum(arr, axis=0))

# Sum along rows
print(np.sum(arr, axis=1))

[5 7 9]
[ 6 15]


In [45]:
arr = np.array([[10, 20], [30, 40]])

print(np.mean(arr, axis=0))  # Mean along columns
print(np.mean(arr, axis=1))  # Mean along rows

[20. 30.]
[15. 35.]


In [ ]:
# Broadcasting and aggregation functions can be combined to process data efficiently.

arr = np.array([[1, 2, 3], [4, 5, 6]])

mean = np.mean(arr, axis=0)  # Compute column-wise mean
result = arr - mean          # Subtract column means
print(result)

# iteration

In [45]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Iterate through each element
for element in arr:
    print(element)

10
20
30
40
50


In [46]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterate through each row
for row in arr_2d:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [47]:
# Iterate through each element in a 2D array
for row in arr_2d:
    for element in row:
        print(element, end=' ')


1 2 3 4 5 6 7 8 9 

## nditer()

`np.nditer()` provides a flexible and efficient way to iterate over multi-dimensional arrays. It allows you to iterate over the entire array, regardless of its dimensionality.

In [63]:
# 1D array example
arr = np.array([10, 20, 30, 40, 50])

for element in np.nditer(arr):
    print(element)

10
20
30
40
50


In [64]:
# 2D array example
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for element in np.nditer(arr_2d):
    print(element, end=' ')

1 2 3 4 5 6 7 8 9 

By default, NumPy's `nditer()` iterates element by element. You can modify this behavior using `::step` slicing in 1D or 2D arrays.

In [49]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Iterate with a step of 2
for element in arr[::2]:
    print(element)

10
30
50


By default, `nditer()` doesn't allow modification of the elements during iteration. To modify elements, you need to explicitly enable write mode using the `op_flags=['readwrite']` option.

In [50]:
arr = np.array([1, 2, 3, 4, 5])

# Modify array elements by multiplying each element by 2
for element in np.nditer(arr, op_flags=['readwrite']):
    element[...] = element * 2

print(arr)  # Output: [ 2  4  6  8 10]

[ 2  4  6  8 10]


In [51]:
# Iterating Over Multiple Arrays Simultaneously

arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

# Iterate over both arrays simultaneously
for x, y in np.nditer([arr1, arr2]):
    print(f"{x} * {y} = {x * y}")

1 * 10 = 10
2 * 20 = 40
3 * 30 = 90


For higher-dimensional arrays like 3D, you can use the same approach as with 2D arrays. `nditer()` makes it easy to handle any number of dimensions.

In [52]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Iterate through each element in a 3D array
for element in np.nditer(arr_3d):
    print(element, end=' ')

1 2 3 4 5 6 7 8 

`np.ndenumerate()` is useful when you want to iterate through the array and get both the index and the value of each element.

In [67]:
arr = np.array([10, 20, 30])

# Enumerate over a 1D array
for index, value in np.ndenumerate(arr):
    print(f"Index {index}, Value {value}")

Index (0,), Value 10
Index (1,), Value 20
Index (2,), Value 30


In [68]:
# 2D array example
arr_2d = np.array([[1, 2], [3, 4]])
for index, value in np.ndenumerate(arr_2d):
    print(f"Index {index}, Value {value}")

Index (0, 0), Value 1
Index (0, 1), Value 2
Index (1, 0), Value 3
Index (1, 1), Value 4


# copy and view

In NumPy, the concepts of copy and view play a crucial role in memory management and data manipulation. Understanding the distinction between them is important when working with arrays to ensure that changes in one array do not unintentionally affect another.

## copy in NumPy

A copy of an array creates a completely new array in memory. The new array is independent of the original array, meaning that changes made to the copy will not affect the original array, and vice versa.

In [54]:
import numpy as np

arr = np.array([10, 20, 30, 40])

# Create a copy of the array
arr_copy = arr.copy()

# Modify the copy
arr_copy[0] = 100

print("Original array:", arr)  # Output: [10 20 30 40]
print("Modified copy:", arr_copy)  # Output: [100  20  30  40]

Original array: [10 20 30 40]
Modified copy: [100  20  30  40]


## view in NumPy

A view (or a shallow copy) is a new array object that looks at the same data as the original array. This means that changes made to the view will affect the original array, and changes made to the original array will also affect the view. No new data is created in memory; the view just references the same data.

In [55]:
arr = np.array([10, 20, 30, 40])

# Create a view of the array
arr_view = arr.view()

# Modify the view
arr_view[0] = 100

print("Original array:", arr)  # Output: [100  20  30  40]
print("Modified view:", arr_view)  # Output: [100  20  30  40]

Original array: [100  20  30  40]
Modified view: [100  20  30  40]


## copy vs view

<table><thead><tr><th><strong>Feature</strong></th><th><strong>Copy</strong></th><th><strong>View</strong></th></tr></thead><tbody><tr><td><strong>Memory</strong></td><td>New array with new data is created</td><td>No new data, shares the original data</td></tr><tr><td><strong>Modifications</strong></td><td>Changes in the copy do not affect the original array</td><td>Changes in the view affect the original array</td></tr><tr><td><strong>Use case</strong></td><td>Use when you need independent data</td><td>Use when you want to avoid copying data for performance reasons</td></tr></tbody></table>

You can check if an array owns its data or is a view of another array using the `.base` attribute.

- If `.base` is `None`, it means the array owns its data (it’s not a view).
- If `.base` is not `None`, it means the array is a view of another array.

In [56]:
# Original array
arr = np.array([10, 20, 30, 40])

# Create a copy
arr_copy = arr.copy()

# Create a view
arr_view = arr.view()

# Check if arrays own their data
print(arr_copy.base)  # Output: None (owns its data)
print(arr_view.base)  # Output: array([10, 20, 30, 40]) (view of the original array)

None
[10 20 30 40]


**Slicing Creates a View, Not a Copy**

When you slice a NumPy array, NumPy creates a view, not a copy. This allows NumPy to be more memory efficient, but it also means that modifying the slice will affect the original array.

In [70]:
arr = np.array([10, 20, 30, 40])

# Create a slice (view)
arr_slice = arr[1:3]

print("sliced array:", arr_slice)  # Output: [20 30]

# Modify the slice
arr_slice[0] = 200

print("Original array:", arr)  # Output: [ 10 200  30  40]
print("Slice:", arr_slice)  # Output: [200  30]


sliced array: [20 30]
Original array: [ 10 200  30  40]
Slice: [200  30]


**When to Use Copy vs. View**
    
- Use a copy when you want to make modifications without affecting the original array.
- Use a view when you want to create a subset or a new representation of the same data, and memory efficiency is important.

**Force a Copy During Slicing**
    
If you want to ensure that slicing returns a copy instead of a view, you can use the copy() method explicitly.

In [58]:
arr = np.array([10, 20, 30, 40])

# Create a copy from a slice
arr_copy = arr[1:3].copy()

# Modify the copy
arr_copy[0] = 200

print("Original array:", arr)  # Output: [10 20 30 40]
print("Modified copy:", arr_copy)  # Output: [200  30]

Original array: [10 20 30 40]
Modified copy: [200  30]


# joining

Joining arrays in NumPy means concatenating two or more arrays along a specified axis. You can join arrays using the following functions:

- np.concatenate()
- np.stack()
- np.hstack() (Horizontal stacking)
- np.vstack() (Vertical stacking)

In [61]:
import numpy as np

# Example: 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))

print(result)  # Output: [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [71]:
# Example: 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate([arr1, arr2]) # list

print(result)  # Output: [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [72]:
# Example: 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis=0 (rows)
result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [73]:
# Concatenate along axis=1 (columns)
result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


The `stack()` function joins arrays along a new axis. Unlike `concatenate()`, it adds an additional dimension to the arrays being joined.

In [63]:
# Example: Stacking 1D arrays into a 2D array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.stack((arr1, arr2), axis=0)
print(result)

[[1 2 3]
 [4 5 6]]


In [64]:
result = np.stack((arr1, arr2), axis=1)
print(result)

[[1 4]
 [2 5]
 [3 6]]


`hstack()` stacks arrays horizontally (column-wise). It is equivalent to concatenating along axis=1.

In [65]:
# Example: Horizontal stacking
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))
print(result)  # Output: [1 2 3 4 5 6]

[1 2 3 4 5 6]


`vstack()` stacks arrays vertically (row-wise). It is equivalent to concatenating along axis=0.

In [66]:
# Example: Vertical stacking
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))
print(result)

[[1 2 3]
 [4 5 6]]


# splitting

Splitting arrays is the process of dividing one array into multiple sub-arrays. You can split arrays using these functions:

- np.split()
- np.hsplit() (Horizontal split)
- np.vsplit() (Vertical split)

In [67]:
# Example: Split 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 sub-arrays
result = np.split(arr, 3)

print(result)  # Output: [array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [68]:
# Split at indices 2 and 4
result = np.split(arr, [2, 4])

print(result)  # Output: [array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5, 6])]


`hsplit()` splits arrays along the horizontal axis (axis=1 for 2D arrays).

In [69]:
# Example: Horizontal split
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Split horizontally into 2 sub-arrays
result = np.hsplit(arr, 2)
print(result)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


`vsplit()` splits arrays along the vertical axis (axis=0 for 2D arrays).

In [70]:
# Example: Vertical split
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Split vertically into 2 sub-arrays
result = np.vsplit(arr, 2)
print(result)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


# searching

`np.where()` is one of the most useful functions for searching specific conditions in arrays. It returns the indices of the elements that satisfy a given condition.

In [71]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Find indices where elements are greater than 25
result = np.where(arr > 25)

print(result)  # Output: (array([2, 3, 4]),) (indices where the condition is true)
print(arr[result])  # Output: [30 40 50]

(array([2, 3, 4]),)
[30 40 50]


You can also use `np.where()` to return specific values based on a condition (similar to an `if-else`).

In [72]:
# Replace values greater than 25 with 100, others with 0
result = np.where(arr > 25, 100, 0)

print(result)  # Output: [  0   0 100 100 100]

[  0   0 100 100 100]


# sorting

`np.sort()` returns a sorted copy of an array. It can sort along any axis in multi-dimensional arrays.

In [73]:
arr = np.array([40, 10, 50, 30, 20])

# Sort the array
sorted_arr = np.sort(arr)
print(sorted_arr)  # Output: [10 20 30 40 50]

[10 20 30 40 50]


In [74]:
arr = np.array([[3, 1, 2], [6, 4, 5]])

# Sort along axis=1 (sort rows)
sorted_arr = np.sort(arr, axis=1)
print(sorted_arr)  # Output: [[1 2 3]
                   #          [4 5 6]]

# Sort along axis=0 (sort columns)
sorted_arr = np.sort(arr, axis=0)
print(sorted_arr)  # Output: [[3 1 2]
                   #          [6 4 5]]


[[1 2 3]
 [4 5 6]]
[[3 1 2]
 [6 4 5]]


`argsort()` returns the indices that would sort the array. This is useful when you need the sorted indices rather than the sorted values.

In [75]:
arr = np.array([40, 10, 50, 30, 20])

# Get indices of sorted array
sorted_indices = np.argsort(arr)
print(sorted_indices)  # Output: [1 4 3 0 2]

# Use the indices to sort the array
sorted_arr = arr[sorted_indices]
print(sorted_arr)  # Output: [10 20 30 40 50]

[1 4 3 0 2]
[10 20 30 40 50]


`searchsorted()` returns the index where a given value would fit in a sorted array.

In [76]:
arr = np.array([10, 20, 30, 40, 50])

# Search for the index where 25 should be inserted
index = np.searchsorted(arr, 25)
print(index)  # Output: 2 (25 fits between 20 and 30)

2


In [77]:
values = [15, 35]
indices = np.searchsorted(arr, values)
print(indices)  # Output: [1 3]

[1 3]


# filtering

Filtering is the process of extracting elements that meet a certain condition. This is often done using boolean arrays or conditions.

**Using Boolean Indexing for Filtering**: You can create a boolean mask (True/False) to filter elements that satisfy a condition.

In [78]:
arr = np.array([10, 20, 30, 40, 50])

# Create a boolean mask where values are greater than 25
mask = arr > 25

# Use the mask to filter the array
filtered_arr = arr[mask]
print(filtered_arr)  # Output: [30 40 50]

[30 40 50]


`extract()` returns elements that satisfy a specific condition.

In [79]:
# Extract elements greater than 25
filtered_arr = np.extract(arr > 25, arr)
print(filtered_arr)  # Output: [30 40 50]

[30 40 50]


`nonzero()` returns the indices of elements that are non-zero (or `True` for boolean arrays).

In [80]:
# Example: Find indices of non-zero elements
arr = np.array([0, 1, 2, 0, 3])

result = np.nonzero(arr)
print(result)  # Output: (array([1, 2, 4]),) (indices of non-zero elements)

(array([1, 2, 4]),)


In [81]:
# Find indices where arr > 25
indices = np.nonzero(arr > 25)
print(indices)

(array([], dtype=int64),)


# shuffle

The `shuffle()` function randomly permutes the elements of a 1D array or shuffles the rows of a multi-dimensional array in-place, meaning it changes the original array.

In [82]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)  # Output: Randomly shuffled version of [1, 2, 3, 4, 5]

[2 4 3 5 1]


In [83]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.random.shuffle(arr)
print(arr)  # Output: Randomly shuffled rows

[[1 2 3]
 [7 8 9]
 [4 5 6]]


# unique

The `unique()` function returns the sorted unique elements of an array. It can also return additional information, such as the indices of the unique elements and their counts.

In [84]:
arr = np.array([1, 2, 2, 3, 3, 3, 4])
unique_arr = np.unique(arr)
print(unique_arr)  # Output: [1 2 3 4]

[1 2 3 4]


You can get more information by using the `return_counts` or `return_index` parameters.

In [85]:
# Return unique elements and their counts
unique_arr, counts = np.unique(arr, return_counts=True)
print(unique_arr)  # Output: [1 2 3 4]
print(counts)      # Output: [1 2 3 1] (frequency of each unique element)

[1 2 3 4]
[1 2 3 1]


In [86]:
# Return unique elements and the indices of their first occurrence
unique_arr, indices = np.unique(arr, return_index=True)
print(unique_arr)  # Output: [1 2 3 4]
print(indices)     # Output: [0 1 3 6] (indices of first occurrence)

[1 2 3 4]
[0 1 3 6]


# resize

The `resize()` function returns a new array with the specified shape. If the new size is larger than the original, the array is repeated to fill the new shape. Unlike `reshape()`, `resize()` can change the size of the array (both increasing and decreasing).

In [87]:
arr = np.array([1, 2, 3, 4])

# Resize to a larger array (elements are repeated)
resized_arr = np.resize(arr, (2, 5))
print(resized_arr)  
# Output:
# [[1 2 3 4 1]
#  [2 3 4 1 2]]

[[1 2 3 4 1]
 [2 3 4 1 2]]


In [88]:
# Resize to a smaller array
resized_arr = np.resize(arr, (2, 2))
print(resized_arr)
# Output:
# [[1 2]
#  [3 4]]

[[1 2]
 [3 4]]


# flatten

The `flatten()` function returns a copy of the array collapsed into one dimension. This is helpful for turning a multi-dimensional array into a 1D array.

In [89]:
arr = np.array([[1, 2], [3, 4]])

# Flatten the array
flattened_arr = arr.flatten()
print(flattened_arr)  # Output: [1 2 3 4]

[1 2 3 4]


# ravel

The `ravel()` function also collapses an array into one dimension, but it returns a view whenever possible (i.e., it doesn't always create a new copy of the data).

In [90]:
arr = np.array([[1, 2], [3, 4]])

# Ravel the array
raveled_arr = arr.ravel()
print(raveled_arr)  # Output: [1 2 3 4]

[1 2 3 4]


**Difference Between `flatten()` and `ravel()`:**
    
- flatten() always returns a copy of the original array, and modifications to the flattened array don’t affect the original.
- ravel() returns a view whenever possible, meaning changes to the raveled array might affect the original array (if the original is contiguous in memory).

In [91]:
# Modify a raveled array
raveled_arr[0] = 10
print(arr)  # Output: [[10  2] [3 4]] (original array modified)

[[10  2]
 [ 3  4]]


# insert

The `np.insert()` function inserts values into an array at a specified index or along a given axis.

In [ ]:
np.insert(arr, obj, values, axis=None)

- arr: The input array.
- obj: The index (or indices) at which the values are inserted.
- values: The values to insert.
- axis: The axis along which to insert. If None, the array is flattened before inserting.

In [92]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# Insert 100 at index 2
new_arr = np.insert(arr, 2, 100)
print(new_arr)  # Output: [  1   2 100   3   4]

[  1   2 100   3   4]


When inserting into a 2D array, the axis parameter determines whether to insert along rows or columns:

- axis=0: Insert along rows.
- axis=1: Insert along columns.

In [93]:
arr = np.array([[1, 2], [3, 4]])

# Insert [5, 6] as a new row at index 1
new_arr = np.insert(arr, 1, [5, 6], axis=0)
print(new_arr)  
# Output:
# [[1 2]
#  [5 6]
#  [3 4]]

# Insert [5, 6] as a new column at index 1
new_arr = np.insert(arr, 1, [5, 6], axis=1)
print(new_arr)
# Output:
# [[1 5 2]
#  [3 6 4]]

[[1 2]
 [5 6]
 [3 4]]
[[1 5 2]
 [3 6 4]]


**Note:** When inserting along an axis, the values must match the shape of the row/column you're inserting.

# delete

The `np.delete()` function removes elements from an array at the specified index or along a given axis.

In [ ]:
np.delete(arr, obj, axis=None)

- arr: The input array.
- obj: The index (or indices) of the elements to delete.
- axis: The axis along which to delete. If None, the array is flattened before deletion.

In [94]:
arr = np.array([1, 2, 3, 4, 5])

# Delete the element at index 2
new_arr = np.delete(arr, 2)
print(new_arr)  # Output: [1 2 4 5]

[1 2 4 5]


When working with 2D arrays, you can specify the axis to delete rows or columns:

- axis=0: Deletes rows.
- axis=1: Deletes columns.

In [95]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Delete the row at index 1
new_arr = np.delete(arr, 1, axis=0)
print(new_arr)
# Output:
# [[1 2 3]
#  [7 8 9]]

# Delete the column at index 1
new_arr = np.delete(arr, 1, axis=1)
print(new_arr)
# Output:
# [[1 3]
#  [4 6]
#  [7 9]]

[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


In [96]:
arr = np.array([1, 2, 3, 4, 5])

# Delete elements at indices 1 and 3
new_arr = np.delete(arr, [1, 3])
print(new_arr)  # Output: [1 3 5]

[1 3 5]


# update

You can update elements in a NumPy array by assigning new values to specific positions or slices using indexing.

In [97]:
import numpy as np

# Original array
arr = np.array([1, 2, 3, 4, 5])

# Update the element at index 2 (third element)
arr[2] = 100
print(arr)  # Output: [  1   2 100   4   5]

[  1   2 100   4   5]


In [98]:
# Update elements at indices 1, 2, and 3
arr[1:4] = [20, 30, 40]
print(arr)  # Output: [  1  20  30  40   5]

[ 1 20 30 40  5]


In [99]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Update the element at row 1, column 2
arr[1, 2] = 100
print(arr)
# Output:
# [[  1   2   3]
#  [  4   5 100]
#  [  7   8   9]]

[[  1   2   3]
 [  4   5 100]
 [  7   8   9]]


In [100]:
# Update entire row 1
arr[1] = [10, 20, 30]
print(arr)
# Output:
# [[  1   2   3]
#  [ 10  20  30]
#  [  7   8   9]]

[[ 1  2  3]
 [10 20 30]
 [ 7  8  9]]


**Updating Based on Conditions:** You can update array elements based on conditions using boolean masking.

In [101]:
arr = np.array([1, 2, 3, 4, 5])

# Update all elements greater than 3 to 100
arr[arr > 3] = 100
print(arr)  # Output: [  1   2   3 100 100]

[  1   2   3 100 100]


In [102]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Update all elements greater than 5 to 0
arr[arr > 5] = 0
print(arr)
# Output:
# [[1 2 3]
#  [4 5 0]
#  [0 0 0]]

[[1 2 3]
 [4 5 0]
 [0 0 0]]


You can use NumPy’s in-place arithmetic operations (e.g., +=, -=, *=, /=) to update the elements of an array.

In [103]:
arr = np.array([1, 2, 3, 4, 5])

# Add 10 to each element
arr += 10
print(arr)  # Output: [11 12 13 14 15]

# Multiply each element by 2
arr *= 2
print(arr)  # Output: [22 24 26 28 30]

[11 12 13 14 15]
[22 24 26 28 30]


In [104]:
# Subtract 5 from elements at indices 1 to 3
arr[1:4] -= 5
print(arr)  # Output: [22 19 21 23 30]

[22 19 21 23 30]


NumPy’s broadcasting feature allows you to update an entire array or sub-arrays with a scalar or smaller array.

In [105]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Add 10 to each element
arr += 10
print(arr)
# Output:
# [[11 12 13]
#  [14 15 16]
#  [17 18 19]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [106]:
# Add a 1D array to each row of the 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr += np.array([10, 20, 30])
print(arr)
# Output:
# [[11 22 33]
#  [14 25 36]
#  [17 28 39]]

[[11 22 33]
 [14 25 36]
 [17 28 39]]


#  Statistical Functions

## np.percentile

Percentiles are used to divide a dataset into 100 equal parts, providing a measure to understand the distribution of data. For example:

- The 25th percentile (first quartile) marks the point below which 25% of the data lies.
- The 50th percentile (median) marks the middle of the dataset.
- The 75th percentile (third quartile) marks the point below which 75% of the data lies.

**Syntax:** np.percentile(a, q, axis=None, interpolation='linear', keepdims=False)

- a: Input array.
- q: Percentile(s) to compute (e.g., 25 for 25th percentile).
- axis: The axis along which to compute percentiles. Default is None (flattened array).
- interpolation: Specifies how to handle when the desired percentile lies between two data points:
    - 'linear' (default): Interpolates linearly.
    - 'nearest': Chooses the nearest data point.
    - 'lower'/'higher': Chooses the lower/higher data point.
    - 'midpoint': Takes the average of the two middle points.
- keepdims: If True, the output retains reduced dimensions.

In [56]:
data = [1, 2, 3, 4, 5]
percentiles = np.percentile(data, [25, 50, 75])
print(percentiles)

[2. 3. 4.]


In [57]:
data = np.array([[10, 20, 30], [40, 50, 60]])
median_rows = np.percentile(data, 50, axis=1)
median_cols = np.percentile(data, 50, axis=0)

print("Median along rows:", median_rows)
print("Median along columns:", median_cols)

Median along rows: [20. 50.]
Median along columns: [25. 35. 45.]


## np.corrcoef

Correlation measures the linear relationship between two variables, with values ranging from -1 to 1:

- 1: Perfect positive correlation.
- -1: Perfect negative correlation.
- 0: No linear relationship.

**Syntax:** np.corrcoef(x, y=None, rowvar=True)

- x: 1D or 2D array of data.
- y: Optional second set of data.
- rowvar: If True, each row is considered a variable; if False, each column is considered a variable.

In [58]:
x = [1, 2, 3, 4, 5]
y = [5, 4, 3, 2, 1]

correlation_matrix = np.corrcoef(x, y)
print(correlation_matrix)

[[ 1. -1.]
 [-1.  1.]]


In [59]:
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
correlation_matrix = np.corrcoef(data, rowvar=False)

print(correlation_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## np.cov

Covariance measures the extent to which two variables change together. Unlike correlation, it isn't normalized, so its magnitude depends on the scale of the data:

- Positive covariance: Variables tend to increase together.
- Negative covariance: One variable increases as the other decreases.

**Syntax:** np.cov(m, y=None, rowvar=True, bias=False, ddof=None)

- m: 1D or 2D array of data.
- y: Optional second set of data.
- rowvar: If True, each row represents a variable; if False, each column represents a variable.
- bias: If True, normalization is by N; otherwise by N-1.
- ddof: Overrides the normalization factor.

In [60]:
x = [1, 2, 3, 4, 5]
y = [5, 4, 3, 2, 1]

covariance_matrix = np.cov(x, y)
print(covariance_matrix)

[[ 2.5 -2.5]
 [-2.5  2.5]]


In [61]:
data = np.array([[1, 2], [2, 3], [3, 4]])
covariance_matrix = np.cov(data, rowvar=False)

print(covariance_matrix)

[[1. 1.]
 [1. 1.]]


# matrix

In NumPy, a matrix is essentially a specialized 2D array. Although NumPy does provide a `matrix` class, it's generally recommended to use the more flexible `ndarray` for handling matrices because ndarray supports higher-dimensional data and is more widely used. Still, both share many common operations.

## Creating a Matrix

Matrices are 2D arrays. You can create them using `np.array()` or, for matrix-specific operations, use `np.matrix()`. However, `np.array()` is preferred in modern usage.

In [107]:
import numpy as np

# Create a 2x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [108]:
# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix addition
C = A + B
print(C)
# Output:
# [[ 6  8]
#  [10 12]]

# Matrix subtraction
D = A - B
print(D)
# Output:
# [[-4 -4]
#  [-4 -4]]

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [109]:
# Matrix multiplication (dot product)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A @ B
print(C)
# Output:
# [[19 22]
#  [43 50]]

# Using np.dot()
D = np.dot(A, B)
print(D)  # Output will be the same as above


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [110]:
# Element-wise multiplication
E = A * B
print(E)
# Output:
# [[ 5 12]
#  [21 32]]

[[ 5 12]
 [21 32]]


In [111]:
A = np.array([[1, 2], [3, 4]])

# Transpose of A
A_T = A.T
print(A_T)
# Output:
# [[1 3]
#  [2 4]]

[[1 3]
 [2 4]]


In [112]:
# 3x3 Identity matrix

I = np.eye(3)
print(I)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [113]:
# Create a diagonal matrix

diag_matrix = np.diag([1, 2, 3])
print(diag_matrix)
# Output:
# [[1 0 0]
#  [0 2 0]
#  [0 0 3]]

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [114]:
# 2x3 matrix of zeros

zeros_matrix = np.zeros((2, 3))
print(zeros_matrix)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]

# 3x2 matrix of ones

ones_matrix = np.ones((3, 2))
print(ones_matrix)
# Output:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [115]:
# Square matrix
A = np.array([[1, 2], [3, 4]])

# Determinant of A
det_A = np.linalg.det(A)
print(det_A)  # Output: -2.0

-2.0000000000000004


In [116]:
# Inverse of A
A_inv = np.linalg.inv(A)
print(A_inv)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [117]:
# Original matrix
A = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape to 3x2 matrix
reshaped_A = A.reshape(3, 2)
print(reshaped_A)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [118]:
# Flatten the matrix
flat_A = A.flatten()
print(flat_A)
# Output: [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [119]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Horizontal stacking
C = np.hstack((A, B))
print(C)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [120]:
# Vertical stacking
D = np.vstack((A, B))
print(D)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes by expanding the smaller array to match the larger one.

In [121]:
A = np.array([[1, 2], [3, 4]])

# Add 10 to each element
A_new = A + 10
print(A_new)
# Output:
# [[11 12]
#  [13 14]]

[[11 12]
 [13 14]]
