## binary, decimal, octal, hexadecimal

In [6]:
print(bin(18))

0b10010


In [7]:
type(bin(18))

str

In [2]:
print(oct(18))

0o22


In [14]:
print(hex(18))

0x12


In [17]:
print(0b10010)
print(0o22)
print(0x12)

18
18
18


In [21]:
print(type(bin(18)))

<class 'str'>


In [25]:
number = 1888

print(oct(number))
hexadecimal_representation = oct(number)[2:]
print(hexadecimal_representation)

0o3540
3540


## For else

In Python we can use for and else together.

To understand this lets take an example here.

In [2]:
# we want to chcek number in list divisible by 5

nums=[12,15,18,21,26]

for i in nums:
    if i%5==0:
        print(i)

15


In [3]:
nums=[12,16,18,21,25]

for i in nums:
    if i%5==0:
        print(i)

25


In [5]:
nums=[12,16,18,20,25]

for i in nums:
    if i%5==0:
        print(i)

20
25


What we want is we want to print only first number. So, in this case we will use break

In [8]:
nums=[12,16,18,20,25]

for i in nums:
    if i%5==0:
        print(i)
        break

20


In [9]:
nums=[10,16,18,20,25]

for i in nums:
    if i%5==0:
        print(i)
        break

10


What if we have numbers and none of the number is divisible by 5.

In [10]:
nums=[12,16,18,21,22]

for i in nums:
    if i%5==0:
        print(i)
        break

As expected we don't get any out here because none of numbers is divisible by 5. 

What we can do here is add `else` and print not found

In [11]:
nums=[12,16,18,21,22]

for i in nums:
    if i%5==0:
        print(i)
        break
    else:
        print("not found")

not found
not found
not found
not found
not found


Okay, here we got "not found" 5 times.

What is happening here is for every iteration it is checking for condition and `else` is for if and thats why for every iteration if this `if` statement return false; it will execute `else` block.

But we don't want that. We don't want execute `else` everytime w ehave iteration. We want to execute else only when entire loop is completed without break. So, what we can do is we just write `else` for `for` not for `if`. 

In [12]:
nums=[12,16,18,21,22]

for i in nums:
    if i%5==0:
        print(i)
        break
else:
    print("not found")

not found


**In simple word, the `else` block will run if loop ends naturally without break; i mean if loop break `else` block will not be executed.**

We can do same with `while` loop as well.

In [1]:
nums=[12,16,18,21,22]
i=0

while i<len(nums):
    if i%5==0:
        print(i)
        break
    i+=1
else:
    print("not found")

0


# ARRAY

In [3]:
import array
arr=array.array('i',[1,2,3,4])
arr

array('i', [1, 2, 3, 4])

In [29]:
help(array.array) # documentation of array method

Help on class array in module array:

class array(builtins.object)
 |  array(typecode [, initializer]) -> array
 |  
 |  Return a new array whose items are restricted by typecode, and
 |  initialized from the optional initializer value, which must be a list,
 |  string or iterable over elements of the appropriate type.
 |  
 |  Arrays represent basic values and behave very much like lists, except
 |  the type of objects stored in them is constrained. The type is specified
 |  at object creation time by using a type code, which is a single character.
 |  The following type codes are defined:
 |  
 |      Type code   C Type             Minimum size in bytes
 |      'b'         signed integer     1
 |      'B'         unsigned integer   1
 |      'u'         Unicode character  2 (see note)
 |      'h'         signed integer     2
 |      'H'         unsigned integer   2
 |      'i'         signed integer     2
 |      'I'         unsigned integer   2
 |      'l'         signed integer    

In [4]:
dir(array.array)

['__add__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'buffer_info',
 'byteswap',
 'count',
 'extend',
 'frombytes',
 'fromfile',
 'fromlist',
 'fromunicode',
 'index',
 'insert',
 'itemsize',
 'pop',
 'remove',
 'reverse',
 'tobytes',
 'tofile',
 'tolist',
 'tounicode',
 'typecode']

In [7]:
help(isinstance)

Help on built-in function isinstance in module builtins:

isinstance(obj, class_or_tuple, /)
    Return whether an object is an instance of a class or of a subclass thereof.
    
    A tuple, as in ``isinstance(x, (A, B, ...))``, may be given as the target to
    check against. This is equivalent to ``isinstance(x, A) or isinstance(x, B)
    or ...`` etc.



In [30]:
arr.buffer_info() # address and size

(2329040874512, 4)

In [38]:
arr.typecode # type

'i'

In [2]:
from array import *

arr2=array('f',[3,6,9])
arr2

array('f', [3.0, 6.0, 9.0])

In [3]:
vals=array('i',[5,9,8,4,2])
print(vals)

vals.append(99)
print(vals)

array('i', [5, 9, 8, 4, 2])
array('i', [5, 9, 8, 4, 2, 99])


In [4]:
vals=array('i',[5,9,8.5,4,2]) # Error
print(vals)

TypeError: integer argument expected, got float

In [5]:
vals=array('i',[5,-9,8,4,2]) 
print(vals)

array('i', [5, -9, 8, 4, 2])


In [6]:
vals=array('I',[5,-9,8,4,2]) # Error
print(vals)

OverflowError: can't convert negative value to unsigned int

In [7]:
vals=array('i',[5,-9,8,4,2]) 
print(vals)

vals.reverse()
print(vals)

array('i', [5, -9, 8, 4, 2])
array('i', [2, 4, 8, -9, 5])


In [8]:
# array is siliar to list so we can access it using index

print(vals[1])

vals[1]=999
print(vals[1])

4
999


In [9]:
# for loop

for i in vals:
    print(i)

2
999
8
-9
5


In [10]:
# copying array

newVals=array(vals.typecode,(a for a in vals))

print(newVals)

array('i', [2, 999, 8, -9, 5])


In [11]:
# while loop

i=0
while i<len(newVals):
    print(newVals[i])
    i+=1

2
999
8
-9
5


In [12]:
# for loop

for i in newVals:
    print(i)

2
999
8
-9
5


## Array from user input

In [47]:
from array import *

arr=array('i',[])

n=int(input("Enter size: "))

for i in range(n):
    x=int(input("Enter element: "))
    arr.append(x)
    
print(arr)

Enter size: 3
Enter: element: 1
Enter: element: 2
Enter: element: 3
array('i', [1, 2, 3])


In [48]:
print(arr.index(2))

1


**Now we want ot work with multidimensional array**

In [50]:
vals=array('i',[5,-9,8,4,2],[5,-9,8,4,2]) # Error
print(vals)

vals.reverse()
print(vals)

TypeError: array() takes at most 2 arguments (3 given)

In [51]:
arr=array('i',[[1,2,3],[4,5,6]])
arr

TypeError: an integer is required (got type list)

**In `array` package does not support multidimensional array. That's where we can use third party package that is  `NumPy`**. 

## NumPy

In [1]:
import numpy as np

a1=np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [53]:
a1=np.array([1,2,3],int) # we can specify type as well

In [54]:
a1

array([1, 2, 3])

In [26]:
a1.dtype

dtype('int32')

In [2]:
# linsapce(start, stop, parts)
# here stop include

arr=np.linspace(0,15,5)
arr

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [61]:
# logsapce(start, stop, parts)
# here stop include

arr=np.linspace(0,16) # by default parts is 50
arr

array([ 0.        ,  0.32653061,  0.65306122,  0.97959184,  1.30612245,
        1.63265306,  1.95918367,  2.28571429,  2.6122449 ,  2.93877551,
        3.26530612,  3.59183673,  3.91836735,  4.24489796,  4.57142857,
        4.89795918,  5.2244898 ,  5.55102041,  5.87755102,  6.20408163,
        6.53061224,  6.85714286,  7.18367347,  7.51020408,  7.83673469,
        8.16326531,  8.48979592,  8.81632653,  9.14285714,  9.46938776,
        9.79591837, 10.12244898, 10.44897959, 10.7755102 , 11.10204082,
       11.42857143, 11.75510204, 12.08163265, 12.40816327, 12.73469388,
       13.06122449, 13.3877551 , 13.71428571, 14.04081633, 14.36734694,
       14.69387755, 15.02040816, 15.34693878, 15.67346939, 16.        ])

In [62]:
# arange(start, stop, step)

arr=np.arange(0,16,6)
arr

array([ 0,  6, 12])

In [63]:
# logspace(start, stop)

arr=np.logspace(1,40,5)
arr

array([1.00000000e+01, 5.62341325e+10, 3.16227766e+20, 1.77827941e+30,
       1.00000000e+40])

In [66]:
for i in arr:
    print('%.2f'%i)

10.00
56234132519.03
316227766016837943296.00
1778279410038922838185969975296.00
10000000000000000303786028427003666890752.00


In [64]:
# xeros()

a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [36]:
# ones()
a2=np.ones(4,int)
a2

array([1, 1, 1, 1])

In [42]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])

print(np.concatenate([ar1,ar2]))

[1 2 3 4 5 6]


In [43]:
print(id(ar1))
print(id(ar2))

2092751724048
2092751723472


In [45]:
ar3=ar1.view()
print(id(ar3))

2092751724240


In [46]:
ar1=np.array([1,2,3])
ar1[1]=9

In [47]:
from numpy import *
w=array([1,23,4])
w

array([ 1, 23,  4])

### What is difference between `np.array` and `array.array` ?

The main difference between `np.array` and `array.array` is that `np.array` is a function provided by the `NumPy library`, whereas `array.array` is a built-in module in Python.

`np.array` creates a NumPy `ndarray object`, which is a multi-dimensional array that can hold elements of any data type. NumPy arrays are designed for scientific computing and numerical operations, and provide a wide range of built-in functions for performing operations on arrays, such as mathematical and logical operations, linear algebra, Fourier transforms, and more. NumPy arrays are also much faster and more memory-efficient than regular Python lists or arrays.

`array.array`, on the other hand, creates an `array object` that can only hold elements of a specific data type, such as integers, floats, or bytes. It is primarily used for working with simple, one-dimensional arrays and is generally not as efficient or flexible as NumPy arrays. However, since it is a built-in module, it does not require any external dependencies and can be used out of the box with Python.

Here's an example that illustrates the difference between `np.array` and `array.array` :-

In [1]:
import numpy as np
import array

# Creating a NumPy array and an array.array object
my_numpy_array = np.array([1, 2, 3, 4])
my_regular_array = array.array('i', [1, 2, 3, 4])

# Performing an element-wise multiplication
result_numpy = my_numpy_array * 2
result_regular = [x * 2 for x in my_regular_array]

print("NumPy array:", result_numpy)      # Output: [2 4 6 8]
print("Regular array:", result_regular)  # Output: [2, 4, 6, 8]

NumPy array: [2 4 6 8]
Regular array: [2, 4, 6, 8]


### What is difference between list and array ?

There are several differences between a `NumPy array` and a `Python list` :

**Data type:** A NumPy array can contain only elements of a single data type, while a Python list can contain elements of different data types.

**Memory allocation:** A NumPy array is allocated in a contiguous block of memory, while a Python list is a collection of pointers to objects in memory.

**Performance:** NumPy arrays are optimized for numerical operations and are much faster and more efficient than Python lists for numerical operations.

**Size and shape:** NumPy arrays have a fixed size and shape, while Python lists can be resized and reshaped dynamically.

**Operations:** NumPy arrays support a wide range of mathematical and logical operations such as matrix multiplication, element-wise addition, etc. which are not available with Python lists.

**Indexing:** NumPy arrays support advanced indexing operations such as slicing, boolean indexing, and fancy indexing, which are not available with Python lists.

Here is an example that illustrates some of these differences:

In [2]:
import numpy as np

# Creating a NumPy array and a Python list
my_array = np.array([1, 2, 3, 4, 5])
my_list = [1, 2, 3, 4]

# Adding an element to the NumPy array and Python list
my_array = np.append(my_array, 5)
my_list.append(5)

print("NumPy array:", my_array)   # Output: [1 2 3 4 5 5]
print("Python list:", my_list)    # Output: [1, 2, 3, 4, 5]

# Performing element-wise addition on the NumPy array and Python list
result_array = my_array + 1
result_list = [x + 1 for x in my_list]

print("NumPy array after addition:", result_array)   # Output: [2 3 4 5 6]
print("Python list after addition:", result_list)    # Output: [2, 3, 4, 5, 6]

# Reshaping the NumPy array and Python list
reshaped_array = my_array.reshape(2, 3)
my_list.pop()
my_list.pop()
reshaped_list = [my_list[:2], my_list[2:]]

print("Reshaped NumPy array:", reshaped_array)   # Output: [[1 2 3], [4 5 5]]
print("Reshaped Python list:", reshaped_list)    # Output: [[1, 2], [3, 4, 5]]

# Indexing the NumPy array and Python list
print("NumPy array slice:", my_array[1:3])   # Output: [2 3]
print("Python list slice:", my_list[1:3])    # Output: [2, 3]

NumPy array: [1 2 3 4 5 5]
Python list: [1, 2, 3, 4, 5]
NumPy array after addition: [2 3 4 5 6 6]
Python list after addition: [2, 3, 4, 5, 6]
Reshaped NumPy array: [[1 2 3]
 [4 5 5]]
Reshaped Python list: [[1, 2], [3]]
NumPy array slice: [2 3]
Python list slice: [2, 3]


## copying array

In [69]:
from numpy import *

In [90]:
arr=array([1,2,8,4,5])

In [91]:
arr=arr+5
arr

array([ 6,  7, 13,  9, 10])

In [92]:
arr1=array([1,2,3,4,5])
arr2=array([1,2,3,4,5])

arr3=arr1+arr2
arr3

array([ 2,  4,  6,  8, 10])

In [93]:
print(log(arr))

[1.79175947 1.94591015 2.56494936 2.19722458 2.30258509]


In [94]:
print(sqrt(arr))

[2.44948974 2.64575131 3.60555128 3.         3.16227766]


In [95]:
print(sum(arr))

45


In [96]:
print(min(arr))
print(max(arr))

6
13


In [97]:
arr=[7,2,4,5,11]

sortArr=sort(arr) # return sorted array

print(sortArr)

[ 2  4  5  7 11]


In [98]:
# If you want to sort the original array in place, you can use the sort() method:

print(arr)

arr.sort() # inpace sort

print(arr)

[7, 2, 4, 5, 11]
[2, 4, 5, 7, 11]


In [100]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

# Sort the array in descending order
sorted_arr_descending = np.sort(arr, kind='quicksort')[::-1]
sorted_arr_descending

array([9, 6, 5, 5, 5, 4, 3, 3, 2, 1, 1])

In [101]:
# copying array

arrCopy=arr

print(arr)
print(arrCopy)

[3 1 4 1 5 9 2 6 5 3 5]
[3 1 4 1 5 9 2 6 5 3 5]


In [102]:
print(id(arr))
print(id(arrCopy))

2329304028624
2329304028624


In [103]:
# create different array

arrCopy=arr.view()

print(arr)
print(arrCopy)

[3 1 4 1 5 9 2 6 5 3 5]
[3 1 4 1 5 9 2 6 5 3 5]


In [104]:
print(id(arr))
print(id(arrCopy))

2329304028624
2329303994416


We got two address here that means we have two array in memory that we have two different variables at two different location.

But there is one little problem here.

When we talk about copy we two differnt types of copy:

1. **Shallow copy:** A shallow copy creates a new object but does not create new copies of the elements within the object. Instead, it creates references to the original elements. In other words, a shallow copy points to the same memory locations as the original object. Changes made to the elements within the shallow copy will affect the original object and vice versa.

2. **Deep copy:** A deep copy creates a new object and recursively creates new copies of all the elements within the object, including nested objects. As a result, a deep copy is independent of the original object, and changes made to the elements within the deep copy do not affect the original object, and vice versa.

In [112]:
# create shallow copy

arr11=array([1,2,3,4])

arrCopy1=arr11.view()

print(id(arr11))
print(id(arrCopy1))

arrCopy1[2]=999

print(arr11)
print(arrCopy1)

print(id(arr11))
print(id(arrCopy1))

2329304029008
2329304029104
[  1   2 999   4]
[  1   2 999   4]
2329304029008
2329304029104


In [114]:
# create deep copy

arr12=array([1,2,3,4])

arrCopy2=arr12.copy()

print(id(arr12))
print(id(arrCopy))

arrCopy2[2]=999

print(arr12)
print(arrCopy1)

print(id(arr12))
print(id(arrCopy2))

2329304027472
2329304027376
[1 2 3 4]
[  1   2 999   4]
2329304027472
2329303903952


# Regular Expression

https://docs.python.org/3/howto/regex.html

https://docs.python.org/3/library/re.html

In [1]:
import re
result=re.search(r'aza','plaza')
print(result)

<re.Match object; span=(2, 5), match='aza'>


**Remark:** Always use raw strings for regular string in Python

In [2]:
result=re.search(r'aza','bazaar')
print(result)

<re.Match object; span=(1, 4), match='aza'>


In [3]:
result=re.search(r'aza','fresh')
print(result)

None


In [4]:
# ^ Starts with

print(re.search(r"^x", "xenon"))

<re.Match object; span=(0, 1), match='x'>


In [45]:
# . Any character (except newline character)

print(re.search(r"p.ng", "penguin"))

<re.Match object; span=(0, 4), match='peng'>


In [6]:
print(re.search(r"p.ng", "clapping"))

<re.Match object; span=(4, 8), match='ping'>


In [7]:
print(re.search(r"p.ng", "sponge"))

<re.Match object; span=(1, 5), match='pong'>


In [8]:
print(re.search(r"p.ng", "Pangeea", re.IGNORECASE)) # ignore the case of string

<re.Match object; span=(0, 4), match='Pang'>


In [46]:
# $ Ends with

print(re.search(r"planet$", "this is planet"))

<re.Match object; span=(8, 14), match='planet'>


In [49]:
# * Zero or more occurrences

print(re.search(r"h.*o", "hello world"))

<re.Match object; span=(0, 8), match='hello wo'>


In [51]:
# + One or more occurrences

print(re.search(r"h.+o", "hello"))

<re.Match object; span=(0, 5), match='hello'>


In [52]:
print(re.search(r"h.+o", "hell"))

None


In [55]:
# ? Zero or one occurrences

print(re.search(r"h.?o", "heo"))

<re.Match object; span=(0, 3), match='heo'>


In [56]:
# {} Exactly the specified number of occurrences

print(re.search(r"he.{2}o", "hello"))

<re.Match object; span=(0, 5), match='hello'>


In [57]:
print(re.search(r"he.{2}o", "helllo"))

None


## Wild cards and Character class

Using a dot is the broadest possible wildcard because it matches absolutely any character. But what if we wanted something stricter, like checking if an answer given by a user contains a valid character, or finding all the usernames in a CSV file that start with a vowel? 

We have to restrict our wildcards to a range of characters to do this. For this task we use another feature of regexes called character classes. 

Character classes are written inside square brackets and let us list the characters we want to match inside of those brackets. For example,

In [9]:
print(re.search(r"[Pp]ython", "Python"))

<re.Match object; span=(0, 6), match='Python'>


In [10]:
print(re.search(r"[a-z]way", "The end of the highway"))

<re.Match object; span=(18, 22), match='hway'>


In [11]:
print(re.search(r"[a-z]way", "What a way to go"))

None


In [12]:
print(re.search(r"cloud[a-zA-Z0-9]", "cloudy"))

<re.Match object; span=(0, 6), match='cloudy'>


In [13]:
print(re.search(r"cloud[a-zA-Z0-9]", "cloud9"))

<re.Match object; span=(0, 6), match='cloud9'>


Sometimes we may want to match any characters that aren't in a group. To do that, we use a circumflex(`^`) inside the square brackets. For example, let's create a search pattern that looks for any characters that's not a letter.

In [14]:
print(re.search(r"[^a-zA-Z]", "This is a sentence with spaces."))

<re.Match object; span=(4, 5), match=' '>


Here, our pattern matched the first space in the sentence. What if we also add a space to the list of characters that we don't want to match?

In [15]:
print(re.search(r"[^a-zA-Z ]", "This is a sentence with spaces."))

<re.Match object; span=(30, 31), match='.'>


If we want to match either one expression or another, we can use the pipe symbol(`|`) to do that. This lets us list alternative options that can get matched. For example, we could have an expression that matches either the word cat or the word dog, like this.

In [16]:
print(re.search(r"cat|dog", "I like cats."))

<re.Match object; span=(7, 10), match='cat'>


In [17]:
print(re.search(r"cat|dog", "I like dogs."))

<re.Match object; span=(7, 10), match='dog'>


In [18]:
print(re.search(r"cat|dog", "I like both dogs and cats."))

<re.Match object; span=(12, 15), match='dog'>


In this string, we actually have two possible matches for our search. But we only get the first one. That's the way the `search()` function works. If we want to get all possible matches, we can do that using the `findall()` function, which is also provided by the re module, like this.

In [19]:
print(re.findall(r"cat|dog", "I like both dogs and cats."))

['dog', 'cat']


## Repetition quantifiers

We wanted to find the longest word in the string, or we wanted to find the host names in a log file by checking for a bunch of alphanumeric characters between brackets. We can do this using another interesting RegEx concept, repeated matches. 

It's quite common to see expressions that include a dot followed by a star. This means that it matches any character repeated as many times as possible including zero. Let's see a couple of examples of this.

In [20]:
print(re.search(r"Py.*n", "Pygmalion"))

<re.Match object; span=(0, 9), match='Pygmalion'>


In plain English, you could read this RegEx as match Py followed by any number of other characters followed by n. But with our dot star combination we expanded the range of the match to the whole word. See how the dot takes a different value for each letter? Let's try a different string, Python programming. What do you think the pattern will match?

In [21]:
print(re.search(r"Py.*n", "Python programming"))

<re.Match object; span=(0, 17), match='Python programmin'>


You might not have been expecting that. Remember, the Star takes as many characters as possible. In programming terms, we say that this behavior is greedy. It's possible to modify the repetition qualifiers to make them less greedy. 

While our pattern could have matched the word Python, it expanded all the way until the last n in the string. If we only wanted our patterns match letters, we should have used the character class instead like this.

In [22]:
print(re.search(r"Py[a-z]*n", "Python programming"))

<re.Match object; span=(0, 6), match='Python'>


In [23]:
print(re.search(r"Py[a-z]*n", "Pyn"))

<re.Match object; span=(0, 3), match='Pyn'>


Other implementations like the one used by Python or by the Egrep command include two additional repetition qualifiers plus(`+`) and question mark(`?`), that can help us construct more complex expressions. Let's check that out. 

The plus character(`+`) matches one or more occurrences of the character that comes before it. So we had the pattern O plus L plus. Let's check it against a few words.

In [24]:
print(re.search(r"o+l+", "goldfish"))

<re.Match object; span=(1, 3), match='ol'>


In [25]:
print(re.search(r"o+l+", "woolly"))

<re.Match object; span=(1, 5), match='ooll'>


In [26]:
print(re.search(r"o+l+", "boil"))

None


The question mark symbol(`?`) is yet another multiplier. It means either zero or one occurrence of the character before it. Let's see how this works.

In [27]:
print(re.search(r"p?each", "To each their own"))

<re.Match object; span=(3, 7), match='each'>


In [28]:
print(re.search(r"p?each", "I like peaches"))

<re.Match object; span=(7, 12), match='peach'>


## Escape character

Let's say, for example, that we wanted to check that a certain string contained a dot as part of it. If we just put a dot there, it would match any character.

In [29]:
print(re.search(r".com", "welcome"))

<re.Match object; span=(2, 6), match='lcom'>


Here, we wanted to match on strings that had.com in them, but we match a string with something else in it. That's not what we wanted. To match an actual dot, we need to use an Escape character, which in the case of regular expressions is a backslash character. So let's add that to our pattern.

In [30]:
print(re.search(r"\.com", "welcome"))

None


By escaping the dot, it no longer matched the word Welcome, and since there's no.com in the string, it returned none. Let's try something that should actually match.

In [32]:
print(re.search(r"\.com", "mydomain.com"))

<re.Match object; span=(8, 12), match='.com'>


By adding the backslash(`\`), we've got this to correctly match what we wanted it to match. We can use a backslash in this way to escape any special characters, including the ones that we haven't even talked about yet.

When we see a pattern that includes a backslash, it could be escaping a special regex character or a special string character.

Python also uses the backslash for a few special sequences that we can use to represent predefined sets of characters. For example, `\w` matches any alphanumeric character including letters, numbers, and underscores. Let's check out a couple of examples.

In [34]:
print(re.search(r"\w*", "This is an example"))

<re.Match object; span=(0, 4), match='This'>


In [35]:
print(re.search(r"\w*", "And_this_is_another"))

<re.Match object; span=(0, 19), match='And_this_is_another'>


There's also `\d` for matching digits, `\s` for matching whitespace characters like space, tab or new line, `\b` for word boundaries and a few others. 

We've now looked into a bunch of syntax for using regular expressions in Python. Armed with all this knowledge, we can start combining these special characters to create patterns to match the text that we want. 

For example, say you had a list of all the countries in the world and you want to check which of those names start and end in a.

In [36]:
print(re.search(r"A.*a", "Argentina"))

<re.Match object; span=(0, 9), match='Argentina'>


In [37]:
print(re.search(r"A.*a", "Azerbaijan"))

<re.Match object; span=(0, 9), match='Azerbaija'>


Surprising maybe, this happened because we didn't specify that we wanted our patterns match the whole string. So while Azerbaijan doesn't finish with A, it does have an A in its name. So it matches our pattern. We need to make our patterns stricter by adding the beginning of a line and end of a line characters.

In [38]:
print(re.search(r"^A.*a$", "Azerbaijan"))

None


In [39]:
print(re.search(r"^A.*a$", "Australia"))

<re.Match object; span=(0, 9), match='Australia'>


Using regular expressions, we can also construct a pattern that would validate if the string is a valid variable name in Python. Do you remember what the rules were? It can contain any number of letters numbers or underscores, but it can't start with a number. So what do you think the validating pattern would look like?

In [41]:
pattern=r"^[a-zA-Z_][a-zA-Z0-9_]*$"
print(re.search(pattern, "_this_is_valid_variable_name"))

<re.Match object; span=(0, 28), match='_this_is_valid_variable_name'>


In [42]:
print(re.search(pattern, "this isn't valid variable"))

None


In [43]:
print(re.search(pattern, "my_variable1"))

<re.Match object; span=(0, 12), match='my_variable1'>


In [44]:
print(re.search(pattern, "2my_variable1"))

None


## Capturing groups

Capturing groups are portions of the pattern that are enclosed in parentheses.

Let's say that we have a list of people's full names. These names are stored as last name, comma, first name. We want to turn this around and create a string that starts with the first name followed by the last name. We can do this using a regular expression with capturing groups. 

Let's see how this works. First we'll create a matching pattern that matches a group of letters followed by a comma, a space, and then another group of letters. To capture our groups, we'll put each group of letters between parentheses like this.

In [59]:
result=re.search(r"^(\w*), (\w*)$", "Lovelace, Ada")
print(result)

<re.Match object; span=(0, 13), match='Lovelace, Ada'>


Remember that `\w` will match letters, numbers, and underscores. The match object has more attributes and methods than the ones shown by print, so we are going to start using them now. Let's look at the output of the groups method.

In [61]:
print(result.groups())

('Lovelace', 'Ada')


Because we defined two separate groups, the group method returns a tuple of two elements. We can also use indexing to access these groups. The first element contains the text matched by the entire regular expression. Each successive element contains the data that was matched by every subsequent match group. So let's look at the element at index 0.

In [62]:
print(result[0])
print(result[1])
print(result[2])

Lovelace, Ada
Lovelace
Ada


In [64]:
"{} {}".format(result[2],result[1])

'Ada Lovelace'

let's put this into a function that would do the rearranging for us. We'll start by defining a function called rearrange_name, that receives a name by parameter.

In [72]:
def rearrange_name(name):
    result=re.search(r"^(\w*), (\w*)$", name)
    if result == None:
        return name
    return "{} {}".format(result[2],result[1])

In [73]:
rearrange_name("Lovelace, Ada")

'Ada Lovelace'

In [74]:
rearrange_name("Ritchie, Dennis")

'Dennis Ritchie'

In [75]:
rearrange_name("Hopper, Grace M.")

'Hopper, Grace M.'

Now, the regular expression didn't match because we used the `\w` character, which only matches letters. And so it didn't recognize the middle initial as part of the given name.

What we need to do here is add the extra characters that we want to allow in the names. In this example we'd want to add spaces and dots. For other names we can also include dashes. So after updating our pattern, this is what our function would look like.

In [76]:
def rearrange_name(name):
    result=re.search(r"^([\w .-]*), ([\w .-]*)$", name)
    if result == None:
        return name
    return "{} {}".format(result[2],result[1])

In [77]:
rearrange_name("Hopper, Grace M.")

'Grace M. Hopper'

## More on quantifiers

We've used the Star, Plus and question mark repetition qualifiers. What if we wanted a pattern that repeats a specific number of times? This could happen if we're processing a line that we know has some specific data in a column, or we know that we want a string of a specific length. In cases like those, we would manually write the same pattern as many times as we need it. But it would be hard to read and hard to maintain. And that's why Python also offers numeric repetition qualifiers. These are written between curly brackets and can be one or two numbers specifying a range. For example, to match any string of exactly five letters, we can use an expression like this one

In [78]:
print(re.search(r"[a-zA-Z]{5}", "a ghost"))

<re.Match object; span=(2, 7), match='ghost'>


In [79]:
print(re.search(r"[a-zA-Z]{5}", "a scary ghost appeared"))

<re.Match object; span=(2, 7), match='scary'>


In this string, we actually have more matches for our search, but we only get the first one. Remember, what we can do to find more matches? That's right, use the findall function, like this.

In [80]:
print(re.findall(r"[a-zA-Z]{5}", "a scary ghost appeared"))

['scary', 'ghost', 'appea']


Now we have an extra match for the word that's actually longer. What if we wanted to match all the words that are exactly five letters long? We can do that using `\b`, which matches word limits at the beginning and end of the pattern, to indicate that we want full words, like this

In [81]:
print(re.findall(r"\b[a-zA-Z]{5}\b", "a scary ghost appeared"))

['scary', 'ghost']


We said that we can also have two numbers in the range. For example, if we wanted to match a range of five to ten letters or numbers, we could use an expression like this one.

In [82]:
print(re.findall(r"\w{5,10}", "i really like strawberries"))

['really', 'strawberri']


These ranges can also be open ended. A number followed by a comma means at least that many repetitions with no upper boundary limited only by the maximum repetitions in the source text.

In [83]:
print(re.findall(r"\w{5,}", "i really like strawberries"))

['really', 'strawberries']


In [84]:
print(re.search(r"s\w{,20}", "i really like strawberries"))

<re.Match object; span=(14, 26), match='strawberries'>


Here we look for a pattern that was an S followed by up to 20 alphanumeric characters. So we got a match for strawberries which starts with S, and is followed by 11 characters.

## Extracting PID

In [85]:
log="July 31 07:51:48 my_computer bad_process[12345]: ERROR Performing package upgrade"

regex=r"\[(\d+)\]"

result=re.search(regex, log)
print(result[1])

12345


Let's walk through it step-by-step.

The first character of the pattern is the backslash, which is used as the escape character. This means that the next character, which is a square bracket here, is treated literally for matching purposes. After the square bracket, comes the first parentheses. Since it isn't escaped, we know it'll be used as a capturing group. The capturing group parentheses are wrapping the backslash d+ symbols.

From our discussion of special characters and repetition qualifiers, we know that this expression will match one or more numerical characters. After the closing parentheses of the capturing group, we have the closing square bracket symbol, also proceeded by the escape character.

After calling the search function, we know that because we're capturing groups in an expression, we can access the matching data by accessing the value at index 1. Let's try our expression on a different string and check that it really works, no matter what the rest of the text is.

In [86]:
result=re.search(regex, "A completely different string that has numbers [34567]")
print(result[1])

34567


But what if our string didn't actually have a block of numbers between the square brackets?

In [87]:
result=re.search(regex, "99 elephants in a [cage]")
print(result[1])

TypeError: 'NoneType' object is not subscriptable

We tried to access the index 1 of a variable that was none. As Python tells us, this isn't something that we can do. So what should we do instead? We should have a function that extracts the process ID or PID when possible, and does something else if not. It's something like this; will start by defining a function called extract_pid.

In [88]:
def extract_pid(log_line):
    regex=r"\[(\d+)\]"
    result=re.search(regex, log_line)
    if result is None:
        return ""
    return result[1]

In [89]:
print(extract_pid(log))

12345


In [90]:
print(extract_pid("99 elephants in a [cage]"))

## Splitting and Replacing

One of these functions is called `split()`. It works similarly to the `split` function that we used before with strings. But instead of taking a string as a separator, you can take any regular expression as a separator. 

For example we may want to split a piece of text into separate sentences. To do that we need to check not only for the dots but also for question marks or exclamation marks since they're also valid sentence endings. It's something like this.

In [91]:
re.split(r"[.?!]", "One sentence. Another one? And the last one!")

['One sentence', ' Another one', ' And the last one', '']

Check out how we are not escaping the characters that we wrote inside the square brackets. That's because anything that's inside the square brackets is taking for the literal character and not for its special meaning. 

Also see how the notation marks aren't present in the resulting list. If we want our split list to include the elements that we're using to split the values we can use capturing parentheses like this.

In [92]:
re.split(r"([.?!])", "One sentence. Another one? And the last one!")

['One sentence', '.', ' Another one', '?', ' And the last one', '!', '']

This gave us both the sentences and notation marks as elements of a list.

Another interesting function provided by the RE module is called `sub()`. It's used for creating new strings by substituting all or part of them for a different string, similar to the `replace` string method but using regular expressions for both the matching and the replacing. 

Let's see this in an example. So we had some logs in our system that included e-mail addresses of users and we wanted to anonymize the data by removing all the addresses. We could do that by using an expression.

In [93]:
re.sub(r"[\w.%+-]+@[\w.-]+", "[REDACTED]", "Received an email for go_nuts95@my.example.com")

'Received an email for [REDACTED]'

The expression that we're using for identifying email addresses has two parts: the part before that at sign and the part after it. Check out the part that comes before the at sign. We include the alphanumeric characters represented by backslash w which includes letters, numbers, and the underscore sign as well as a dot, percentage sign, plus, and dash. After the at sign, we only allow the alphanumeric characters dot and dash. This will match all email addresses as well as some strings that aren't really valid email addresses like an address with two dots. 

In this scenario we want to be better safe than sorry. So we're going to redact anything that looks like an address. If we wanted to validate that the address is an actual email we would need to be a lot stricter. We just use a regular expression for searching in a plain string for replacing. Let's now look at an example using sub where we use regular expressions for the replacing. For that, we'll go back to our code that switched the order of names of people and use sub to create the new string.

In [94]:
re.sub(r"^([\w .-]*), ([\w .-]*)$", r"\2 \1", "Lovelace, Ada")

'Ada Lovelace'

So once again we'd use parentheses to create capturing groups. In the first parameter, we've got an expression that contains the two groups that we want to match: one before the comma and one after the comma. We want to use a second parameter to replace the matching string. We use backslash two to indicate the second captured group followed by a space and backslash one to indicate the first captured group. When referring to captured groups, a backslash followed by a number indicates the corresponding captured group. 

This is a general notation for regular expressions, and it's used by many tools that support regexes, not just Python. We can also use them to match patterns that repeat themselves which use capturing groups as back references.

https://regexcrossword.com/